### ISSUE TITLE
ADD_ELE does not work

### ISSUE THREAD

**Issue by truongbber** [azerty9971/xtend_tuya#15]
I have a device where add_ele doesn't have a values unit, maybe that's why xtend_tuya can't recognize it, is there a way to quickly modify it?
![add ele](https://github.com/azerty9971/xtend_tuya/assets/144942487/ddbfac4d-a1be-486f-9e78-8f74f380a80d)

**Comment by azerty9971** [comment]
Hello,
Sorry for the delay.

Could you send the full diagnostic file please?
![image](https://github.com/azerty9971/xtend_tuya/assets/3135352/1962365c-4063-472e-a0f6-4358183874f1)

That will help me figure out why it's not showing in the Device :).

Have a nice evening,
Azerty

**Comment by azerty9971** [comment]
Bump, without those logs I won't be able to help :)

**Comment by azerty9971** [comment]
Hello,
Could you try with the latest beta version?

Please make sure to configure a Tuya IOT platform account (like for the old Tuya integration) using the "Configure" button in the Xtended Tuya configuration page:
![image](https://github.com/azerty9971/xtend_tuya/assets/3135352/8fb22ce4-1b61-405e-a461-71d1f4c5c391)
To use this new feature, go to the integration page then next to your username hit "configure":
You'll be prompted with the exact same window as the previous Tuya integration.
To retrieve the information, you have to follow this guide:
0- Before you start, in the IOT platform make sure that you selected the data center of your region on the top right (IMPORTANT)
1- Configure your Tuya IOT platform developer account: https://developer.tuya.com/en/docs/iot/Platform_Configuration_smarthome?id=Kamcgamwoevrx
2- Input the required credentials: https://developer.tuya.com/en/docs/iot/Home-assistant-tuya-intergration?id=Kb0eqjig0utdd

Once it's configured, I recommend to restart Home Assistant (in theory it's not needed but it's safer since this is an early beta).
