### ISSUE TITLE
 Another question about usage

### ISSUE THREAD

**Issue by MarGal79** [azerty9971/xtend_tuya#2]
Hi.

First of all, thank you very much for your work. I appreciate it very much.
I used your energy sensor with Utility meter helper to get daily energy consumption. It worked well at first but after a while I have strange results. After a short time after switching on, the energy sensor seems to no longer register consumption (see picture), even though the device is connected to a tuya socket and is working. The device that is connected to the tuya socket often turns on and off (electric heater) and the rieman intergration gives me wrong results. From 02:00 until 06:00 wifi is turned off. 
What can I do? Please help!

Mario

![pic](https://github.com/azerty9971/xtend_tuya/assets/148633772/3a96d64c-4b8a-42b4-84ab-2e5af2ee4e2e)

**Comment by azerty9971** [comment]
Hello Mario,
Thank your kind words!!

The graph that you shared shouldn't look like this at all, it should be going up only (see below)
![image](https://github.com/azerty9971/xtend_tuya/assets/3135352/9fb5b6a4-95e8-43cc-b759-a776d8804997)

Multiple things could cause this:
- Are you on the latest version of the code of this plugin (the one posted on November 20)? (because that update fixed something that could cause just that)
- Are you restarting your Home Assistant regularly? Because right now when you restart it it resets the consumption instead of retrieving the last known value at boot
- Did you perform the setup of this plugin with exactly the same credentials / country, ... then the original tuya? (like below)
![image](https://github.com/azerty9971/xtend_tuya/assets/3135352/e8f87249-46ab-48a7-aa31-4781c533fa40)
then
![image](https://github.com/azerty9971/xtend_tuya/assets/3135352/0167f8f0-6b9e-46f8-976c-3677804413f7)


Also, the way this plugin works is by listening to the add_ele events that are sent by Tyua's cloud, these event contain the consumption between the last event and now, so if your Home Assistant is offline / off and Tuya send's such a message then you won't take it into account and the end result will be wrong (inferior to the actual consumption)

I'm going to try to investigate so that the last sum of consumption is fetched back upon reboot, this could fix your issue

**Comment by MarGal79** [comment]
Hi Azerty!
Thanks for fast reply.
Of course, I understand that graph should go only up, because total consumption can only rise.
I didnt have latest version so I updated it now. I will try and send you report.
Yes, I do often restart of HA.
Setup is correct because I use it on regular tuya.

Thank you for your efforts and work for now and in the future.

Greetings from Croatia

**Comment by MarGal79** [comment]
Hi Azerty!
Merry Christmas and happy New Year!
Since the last time we spoke, your integration is working well for me. I stopped resetting HA. Thank you very much for your help and effort and best wishes!

**Comment by azerty9971** [comment]
<3
