### ISSUE TITLE
Should this add-on work with local tuya integration?

### ISSUE THREAD

**Issue by kartturikartturi** [azerty9971/xtend_tuya#5]
Hi,
I have Homeassistant  OS 11.4 and Home assistant Core 2024.1.3 installed. I use local tuya integration and tried to install your add-on. I have made directory and copied files to it. I restarted home assistant but I cant find your add-on Hacs -> Integrations.

Please assist.

**Comment by azerty9971** [comment]
Hello,
I don't know if this will work with localtuya. This add-on is meant to be used with the "regular" tuya...

Also, to add it, it's not in HACS but in the regular integrations :).

Have a nice day,
Azerty

**Comment by Rilkf** [comment]
Hi, like the user above, I'm using local tuya integration and I tried to install your integration.
In my case the integration show up but when i press it, nothing happens
![2024-04-11 17_29_46-Settings – Home Assistant – Mozilla Firefox](https://github.com/azerty9971/xtend_tuya/assets/103143375/85174f84-8a7a-4e4a-b011-9675c79e57e9)
![2024-04-11 17_28_47-Settings – Home Assistant – Mozilla Firefox](https://github.com/azerty9971/xtend_tuya/assets/103143375/1ef4089f-708b-449f-b18e-878fee5be475)

Any idea?

![2024-04-11 17_33_02-Settings – Home Assistant – Mozilla Firefox](https://github.com/azerty9971/xtend_tuya/assets/103143375/8d8c309d-8311-41be-b201-092454d35de7)

**Comment by azerty9971** [comment]
Hello,
I've never used localtuya myself, do you have a good tutorial on how to start using it?
Do you need to flash your devices for it to work?
I'll try to look into it but for now the xtend_tuya integration is only compatible with the regular tuya integration.

Have a nice day,
Azerty

**Comment by Rilkf** [comment]
Hi,
I followed this tutorial: 
https://www.youtube.com/watch?v=vq2L9c5hDfQ

You don't need to do anything on the devices. You just need to extract the keys from each device somehow (as shown in the video above) and add the integration via HACS.

Unfortunately, I was unable to extract the local keys via the Tuya developer account. Instead, I used this method (which I am still using to extract local keys from the Smart Life App):
https://www.youtube.com/watch?v=YKvGYXw-_cE&

I'm not so good with coding, but if you need assistance in any way, here I am :D

**Comment by azerty9971** [comment]
Hello,
I've tested with LocalTuya and it uses a completely different approach.
I don't think it would work with it.

The think with LocalTuya is that you are pulling values directly from the device, but the plug is supposed to send delta consumptions (so the consumption that occured between now and the previous delta consumption message).
If you do this using LocalTuya, there is no way to reliably tell for which time frame the delta consumption you are pulling in is applying to. (Because you could have multiple delta consumptions with the same value that follow each other)

If you find a way to fix this issue then it becomes possible to implement the energy consumption in LocalTuya (but I'll be a totally new project because LocalTuya and regular Tuya integrations are totally different).

Have a nice evening,
Azerty
