### ISSUE TITLE
login Error

### ISSUE THREAD

**Issue by bierlaagh** [azerty9971/xtend_tuya#7]
adding my details gives me a login error.
restarted HA checked credentials and dev keys.

sproblem still exist.

**Comment by bierlaagh** [comment]
using IOT DEV id en secret in the first fields and my Tuya credentials in the last fields
<img width="404" alt="Scherm­afbeelding 2024-01-24 om 20 32 58" src="https://github.com/azerty9971/xtend_tuya/assets/1626560/1bdce415-04cd-4d46-aaf4-129729532cb7">

**Comment by azerty9971** [comment]
Hello,
Did you use the same credentials (same country and all other fields) that you've used for the Tuya integration?

Because the extended tuya overrides the tunnel created by the tuya integration. (So you need to first configure the regular tuya integration then enter the same credentials in the xtendtuya one)

I hope this helps :).

Azerty

**Comment by bierlaagh** [comment]
tuya intergration was already installed 
app and integration both use the Netherlands as country.
is there a location where to find debug information that could help?

**Comment by azerty9971** [comment]
Yes

In Settings -> System -> Logs you'll most likely have a line in red regarding the integration.

Else, you can set the log level in your configuration.yaml to debug for the integration.

Something like :

Logger:
custom_component/xtend_tuya: debug

(Check the exact syntax because I'm giving it from memory since I'm not in front of a PC)

**Comment by bierlaagh** [comment]
resolved bij creating a new IOT Token.
Reinstalled Tuya en after that the Tuya extend worked with the new token
